name: .NET Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Garante que o histórico completo seja baixado
        
    - name: List files for debugging
      run: ls -R
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Debug current directory
      run: pwd
  
    - name: Restore dependencies
      run: dotnet restore
      working-directory: github4women

    - name: Build project
      run: dotnet build --configuration Release --no-restore
      working-directory: github4women
            
    - name: Custom script - Log execution time
      run: echo "Workflow executado em $(date)"
