name: .NET Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore github4women/github4women.csproj

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    # Script personalizado para exibir a data e hora da execução
    - name: Custom script - Log execution time
      run: echo "Workflow executado em $(date)"
